 name 			= "Enclave Server"; // Name of your mod
 author 		= "Silence, Stevio"; // Affects Arma 3 Launcher, when the mod are loaded as local
 logo 			= "\enclave_common\logo_ca.paa"; // Logo displayed in the main menu
 logoOver 	    = "\enclave_common\logo_ca.paa"; // When the mouse is over, in the main menu
 tooltip 		= "Enclave";
 tooltipOwned   = "Silence, Stevio"; // Tool tip displayed when the mouse is left over, in the main menu
 picture 		= "\enclave_common\logo_ca.paa"; // Picture displayed from the expansions menu. Optimal size is 2048x1024
 actionName     = "Discord Link";
 action 		= ""; // Website URL, that can be accessed from the expansions menu
 overview 		= ""; // Supports structured text
 hideName 		= 0; // Hide the extension name
 hidePicture	= 0;	// Hide the extension menu
 dlcColor[] 	= {0.23,0.39,0.30,1}; // Color used for DLC stripes and backgrounds (RGBA)
 logoSmall 		= "\enclave_common\logo_ca.paa"; // Display in creative lists, next to the entities added by the mod